"""Endpoint tests for Route Handlers, Server Actions, and Edge Functions.

Plain HTTP against a running deployment, generated as Vitest. No browser, so
these are fast and stable — worth preferring wherever a real seam exists rather
than driving the same behaviour through the interface.

The default assertion for an unauthenticated request against a mutating
endpoint is that it is *refused*. Server Actions in particular look like local
function calls while actually being unauthenticated-by-default RPC endpoints,
and "anyone on the internet can call this" is the most common real defect in
that surface.
"""

from __future__ import annotations

from typing import ClassVar

from testtrout.authoring.base import EmittedFile, header, ts_string
from testtrout.domain.config import Config
from testtrout.domain.scenario import AssertionKind, Scenario

SETUP_PATH = "tests/trout/_http.ts"

SETUP_SOURCE = """\
// Generated by testtrout. Shared helpers for endpoint tests.
//
// Do not edit. Regenerated by `trout generate`.
function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is not set — see .env and .trout/config.yaml.`);
  }
  return value;
}

export const baseUrl = (): string => required('TROUT_BASE_URL').replace(/\\/$/, '');

export async function call(
  path: string,
  init: RequestInit = {},
): Promise<{ status: number; body: unknown }> {
  const response = await fetch(`${baseUrl()}${path}`, init);
  let body: unknown = null;
  try {
    body = await response.json();
  } catch {
    body = null;
  }
  return { status: response.status, body };
}
"""


class EndpointEmitter:
    """Emits Vitest HTTP tests."""

    id: ClassVar[str] = "endpoint-vitest"
    handles: ClassVar[tuple[str, ...]] = ("endpoint", "data_operation")

    def emit(self, scenario: Scenario, config: Config) -> EmittedFile:
        """Compile one endpoint scenario."""
        path = f"tests/trout/endpoint/{scenario.id.replace(':', '_')}.test.ts"
        target = next((s.target for s in scenario.when if s.target.url), None) or next(
            (a.target for a in scenario.then if a.target.url), None
        )

        url = (target.url if target else None) or "/"
        method = (target.method if target else None) or "GET"
        expected_status = next(
            (a.expected for a in scenario.then if a.kind is AssertionKind.STATUS), None
        )

        notes: list[str] = []
        if expected_status is None:
            notes.append(
                f"{scenario.id}: no expected status was specified, so the test only asserts "
                "the endpoint does not return a server error. Tighten it before relying on it."
            )
            check = "expect(status, `${status} from the endpoint`).toBeLessThan(500);"
        else:
            check = (
                f"expect(status, `expected {expected_status}, got ${{status}}`)"
                f".toBe({expected_status});"
            )

        evidence = "\n".join(
            f"// {a.provenance.value}: {a.source}" for a in scenario.then if a.source
        )

        return EmittedFile(
            path=path,
            content=header(scenario.id)
            + f"""
import {{ describe, expect, it }} from 'vitest';

import {{ call }} from '../_http';

{evidence}
describe({ts_string(scenario.title)}, () => {{
  it({ts_string(scenario.title)}, async () => {{
    const {{ status }} = await call({ts_string(url)}, {{ method: {ts_string(method)} }});
    {check}
  }});
}});
""",
            shared={SETUP_PATH: SETUP_SOURCE},
            notes=notes,
        )
