"""Browser journey tests, generated as Playwright.

Selector strategy is the whole game here. A generated browser suite is only as
durable as the way it addresses elements, and the usual reason such suites get
abandoned is that they were written against generated class names and broke on
the next restyle.

So selectors come from what the prober actually observed, ranked by durability:
a ``data-testid`` if one exists, then an accessible role and name, then a
label, then visible text. When a screen offers nothing better than text, the
generated file says so in a comment — the honest fix is to add test ids, not to
generate a brittle test quietly.

Sign-in is a shared helper rather than repeated per test, so a change to the
auth flow is one edit to one generated file.
"""

from __future__ import annotations

from typing import ClassVar

from testtrout.authoring.base import EmittedFile, header, ts_string
from testtrout.domain.config import Config
from testtrout.domain.observation import SelectorStrategy
from testtrout.domain.scenario import Action, AssertionKind, Scenario, Step

SETUP_PATH = "tests/trout/_browser.ts"

SETUP_SOURCE = """\
// Generated by testtrout. Shared helpers for browser tests.
//
// Do not edit. Regenerated by `trout generate`.
import { createClient } from '@supabase/supabase-js';
import type { Page } from '@playwright/test';

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is not set — see .env and .trout/config.yaml.`);
  }
  return value;
}

/**
 * Refuse to let the browser reach a substituted third party.
 *
 * A test run must never be able to charge a card or email a customer. Hosts
 * come from `substitution.external` in .trout/config.yaml, which `trout scan`
 * populates from the SDKs it finds in your code.
 *
 * An unmatched request fails loudly rather than passing through. A mock that
 * silently matches nothing is how a suite starts reporting green while testing
 * nothing.
 */
export async function installSubstitutions(page: Page): Promise<void> {
  const hosts = (process.env.TROUT_SUBSTITUTE_HOSTS ?? '')
    .split(',')
    .map((h) => h.trim())
    .filter(Boolean);
  if (hosts.length === 0) return;

  await page.route('**/*', async (route) => {
    const host = new URL(route.request().url()).hostname;
    if (!hosts.some((h) => host === h || host.endsWith(`.${h}`))) {
      return route.continue();
    }
    if (process.env.TROUT_ON_UNMATCHED_REQUEST === 'passthrough') {
      return route.continue();
    }
    // Distinctive text: the runner classifies this as a contract mismatch
    // rather than as a product failure.
    return route.fulfill({
      status: 599,
      contentType: 'application/json',
      body: JSON.stringify({
        error: `unmatched outbound request to ${host} — no substitution contract`,
      }),
    });
  });
}

/**
 * Sign in as a seeded test user.
 *
 * Uses the Supabase Auth API and injects the session, rather than driving the
 * login form. Every app's form is different; the API is not, so this keeps
 * working when the login screen is restyled.
 */
export async function signIn(page: Page, role: string): Promise<void> {
  const upper = role.toUpperCase().replace(/-/g, '_');
  const url = required('SUPABASE_URL');
  const client = createClient(url, required('SUPABASE_ANON_KEY'));

  const { data, error } = await client.auth.signInWithPassword({
    email: required(`TROUT_${upper}_EMAIL`),
    password: required(`TROUT_${upper}_PASSWORD`),
  });
  if (error || !data.session) {
    throw new Error(`could not sign in as ${role}: ${error?.message ?? 'no session'}`);
  }

  const ref = new URL(url).hostname.split('.')[0];
  const key = `sb-${ref}-auth-token`;
  const value = JSON.stringify(data.session);

  await page.addInitScript(
    ([k, v]) => window.localStorage.setItem(k as string, v as string),
    [key, value],
  );
}
"""


class PlaywrightEmitter:
    """Emits Playwright browser tests."""

    id: ClassVar[str] = "playwright"
    handles: ClassVar[tuple[str, ...]] = ("browser_journey",)

    def emit(self, scenario: Scenario, config: Config) -> EmittedFile:
        """Compile one browser scenario."""
        path = f"tests/trout/browser/{scenario.id.replace(':', '_')}.spec.ts"
        notes: list[str] = []

        weak = [
            a.target.selector
            for a in scenario.then
            if a.target.selector and a.target.selector.strategy.rank >= SelectorStrategy.TEXT.rank
        ]
        if weak:
            notes.append(
                f"{scenario.id}: {len(weak)} assertion(s) target elements by visible text, so "
                "this test breaks on a copy change. Adding data-testid attributes to those "
                "elements is the cheapest durable fix."
            )

        lines = [f"    {line}" for line in _body(scenario)]
        return EmittedFile(
            path=path,
            content=header(scenario.id)
            + f"""
import {{ expect, test }} from '@playwright/test';

import {{ installSubstitutions, signIn }} from '../_browser';

test({ts_string(scenario.title)}, async ({{ page }}) => {{
    await installSubstitutions(page);

{chr(10).join(lines)}
}});
""",
            shared={SETUP_PATH: SETUP_SOURCE},
            notes=notes,
        )


def _body(scenario: Scenario) -> list[str]:
    """Render the steps and assertions of a browser scenario."""
    lines: list[str] = []

    for note in scenario.given:
        lines.append(f"// given: {note}")
    if scenario.given:
        lines.append("")

    for step in scenario.when:
        lines.extend(_step(step, scenario))

    if scenario.then:
        lines.append("")
    for assertion in scenario.then:
        lines.extend(_assertion(assertion))

    return lines or ["// no steps were specified"]


def _step(step: Step, scenario: Scenario) -> list[str]:
    """Render one action."""
    comment = [f"// {step.description}"] if step.description else []

    if step.action is Action.SIGN_IN:
        role = step.value or scenario.role or "owner"
        return [*comment, f"await signIn(page, {ts_string(role)});"]

    if step.action is Action.NAVIGATE:
        url = step.target.url or "/"
        return [*comment, f"await page.goto({ts_string(url)});"]

    if step.action is Action.CLICK and step.target.selector:
        return [*comment, f"await page.{step.target.selector.playwright()}.click();"]

    if step.action is Action.FILL and step.target.selector:
        return [
            *comment,
            f"await page.{step.target.selector.playwright()}.fill({ts_string(step.value or '')});",
        ]

    if step.action is Action.WAIT_FOR and step.target.selector:
        return [
            *comment,
            f"await expect(page.{step.target.selector.playwright()}).toBeVisible();",
        ]

    return [*comment, f"// unsupported step: {step.action.value}"]


def _assertion(assertion) -> list[str]:  # type: ignore[no-untyped-def]
    """Render one check, carrying its provenance into the generated file.

    The provenance comment is not decoration. When this test fails at 2am,
    whoever reads it needs to know whether the expectation came from a policy
    or from a model's guess.
    """
    lines: list[str] = []
    if assertion.source:
        lines.append(f"// {assertion.provenance.value}: {assertion.source}")

    selector = assertion.target.selector
    if assertion.kind is AssertionKind.VISIBLE and selector:
        lines.append(f"await expect(page.{selector.playwright()}).toBeVisible();")
    elif assertion.kind is AssertionKind.TEXT and selector:
        lines.append(
            f"await expect(page.{selector.playwright()})"
            f".toContainText({ts_string(assertion.expected or '')});"
        )
    elif assertion.kind is AssertionKind.URL:
        lines.append(f"await expect(page).toHaveURL(/{assertion.expected or '.*'}/);")
    elif assertion.kind is AssertionKind.NO_CONSOLE_ERRORS:
        lines.append("// console errors are collected by the runner, not asserted here")
    else:
        lines.append(f"// unsupported assertion: {assertion.kind.value}")

    return lines
