"""Browser journey tests, generated as Playwright.

Selector strategy is the whole game here. A generated browser suite is only as
durable as the way it addresses elements, and the usual reason such suites get
abandoned is that they were written against generated class names and broke on
the next restyle.

So selectors come from what the prober actually observed, ranked by durability:
a ``data-testid`` if one exists, then an accessible role and name, then a
label, then visible text. When a screen offers nothing better than text, the
generated file says so in a comment — the honest fix is to add test ids, not to
generate a brittle test quietly.

Sign-in is a shared helper rather than repeated per test, so a change to the
auth flow is one edit to one generated file.
"""

from __future__ import annotations

from typing import ClassVar

from testtrout.authoring.base import EmittedFile, header, ts_string
from testtrout.domain.config import Config
from testtrout.domain.observation import SelectorStrategy
from testtrout.domain.scenario import Action, AssertionKind, Scenario, Step

SETUP_PATH = "tests/trout/_browser.ts"

SETUP_SOURCE = """\
// Generated by TestTrout. Shared helpers for browser tests.
//
// Do not edit. Regenerated by `trout generate`.
import { expect, type Page } from '@playwright/test';

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is not set — see .env and .trout/config.yaml.`);
  }
  return value;
}

/**
 * Sign in through the application's own login form.
 *
 * Deliberately not via a database or auth API: those need credentials most
 * teams will not hand over. A URL and a test password are enough, and the form
 * is the path a real user takes anyway.
 *
 * The locators come from `trout probe`, which found this form once so tests do
 * not have to guess at it on every run.
 */
export async function signIn(page: Page, role: string): Promise<void> {
  const upper = role.toUpperCase().replace(/-/g, '_');
  const email = required(`TROUT_${upper}_EMAIL`);
  const password = required(`TROUT_${upper}_PASSWORD`);

  await page.goto(__LOGIN_PATH__);
  await page.__EMAIL_SELECTOR__.fill(email);
  await page.__PASSWORD_SELECTOR__.fill(password);
  __SUBMIT__

  await page.waitForLoadState('networkidle').catch(() => {});

  // Still looking at a password field means the credentials were rejected.
  const stillOnLogin = await page.__PASSWORD_SELECTOR__.count();
  expect(
    stillOnLogin,
    `sign-in as ${role} did not go through — check TROUT_${upper}_EMAIL and ` +
      `TROUT_${upper}_PASSWORD, and that the account exists`,
  ).toBe(0);
}

/**
 * Refuse to let a browser test reach a real third-party service.
 *
 * A test that quietly charges a real card, sends a real email, or calls a
 * vendor's production API is worse than a test that fails: the damage is done
 * before anyone reads the report. So every request to a substituted host is
 * intercepted, and the default for one that matches no contract is to fail the
 * test rather than let it through — a mock that silently matches nothing is
 * how a suite starts reporting green while testing nothing.
 *
 * Hosts come from `substitution.external` in .trout/config.yaml, which
 * `trout scan` populates from the vendors it finds in your source.
 */
export async function installSubstitutions(page: Page): Promise<void> {
  const hosts = (process.env.TROUT_SUBSTITUTE_HOSTS || '')
    .split(',')
    .map((h) => h.trim())
    .filter(Boolean);
  if (hosts.length === 0) {
    return;
  }

  const policy = process.env.TROUT_ON_UNMATCHED_REQUEST || 'fail';
  await page.route('**/*', async (route) => {
    let host: string;
    try {
      host = new URL(route.request().url()).hostname;
    } catch {
      return route.continue();
    }
    // Suffix match so api.stripe.com covers its subdomains, but example.com
    // never matches notexample.com.
    const matched = hosts.some((h) => host === h || host.endsWith(`.${h}`));
    if (!matched) {
      return route.continue();
    }

    if (policy === 'passthrough') {
      return route.continue();
    }
    if (policy === 'record') {
      console.warn(`[trout] unmatched third-party request to ${host}`);
      return route.continue();
    }
    return route.abort('blockedbyclient');
  });
}

/**
 * Text that identifies the rows a signed-in user can see on a screen.
 *
 * Used by authorization tests: what one account can see, another must not.
 */
export async function visibleRowText(page: Page): Promise<string[]> {
  return page.evaluate(() => {
    const rows = document.querySelectorAll(
      '[data-testid], tbody tr, li, article, [role="listitem"], [role="row"]',
    );
    return [...rows]
      .map((el) => (el.textContent || '').replace(/\\s+/g, ' ').trim())
      .filter((t) => t.length > 8 && t.length < 400);
  });
}
"""


class PlaywrightEmitter:
    """Emits Playwright browser tests."""

    id: ClassVar[str] = "playwright"
    handles: ClassVar[tuple[str, ...]] = ("browser_journey",)

    def emit(self, scenario: Scenario, config: Config) -> EmittedFile:
        """Compile one browser scenario."""
        path = f"tests/trout/browser/{scenario.id.replace(':', '_')}.spec.ts"
        notes: list[str] = []

        weak = [
            a.target.selector
            for a in scenario.then
            if a.target.selector and a.target.selector.strategy.rank >= SelectorStrategy.TEXT.rank
        ]
        if weak:
            notes.append(
                f"{scenario.id}: {len(weak)} assertion(s) target elements by visible text, so "
                "this test breaks on a copy change. Adding data-testid attributes to those "
                "elements is the cheapest durable fix."
            )

        lines = [f"    {line}" for line in _body(scenario)]
        return EmittedFile(
            path=path,
            content=header(scenario.id)
            + f"""
import {{ expect, test }} from '@playwright/test';

import {{ installSubstitutions, signIn }} from '../_browser';

test({ts_string(scenario.title)}, async ({{ page }}) => {{
    await installSubstitutions(page);

{chr(10).join(lines)}
}});
""",
            shared={SETUP_PATH: _setup_source(config)},
            notes=notes,
        )


def _setup_source(config: Config) -> str:
    """Bake the discovered login locators into the shared helper.

    Emitting them rather than reading them at runtime keeps the generated
    tests self-contained: they run under plain `npx playwright test` with no
    TestTrout involved.
    """
    login = config.login
    email = login.email_selector or "getByLabel('Email', { exact: false })"
    password = login.password_selector or "locator('input[type=\"password\"]')"
    submit = (
        f"await page.{login.submit_selector}.click();"
        if login.submit_selector
        else f"await page.{password}.press('Enter');"
    )
    return (
        SETUP_SOURCE.replace("__LOGIN_PATH__", ts_string(login.path or "/login"))
        .replace("__EMAIL_SELECTOR__", email)
        .replace("__PASSWORD_SELECTOR__", password)
        .replace("__SUBMIT__", submit)
    )


def _body(scenario: Scenario) -> list[str]:
    """Render the steps and assertions of a browser scenario."""
    lines: list[str] = []

    for note in scenario.given:
        lines.append(f"// given: {note}")
    if scenario.given:
        lines.append("")

    for step in scenario.when:
        lines.extend(_step(step, scenario))

    if scenario.then:
        lines.append("")
    for assertion in scenario.then:
        lines.extend(_assertion(assertion))

    return lines or ["// no steps were specified"]


def _step(step: Step, scenario: Scenario) -> list[str]:
    """Render one action."""
    comment = [f"// {step.description}"] if step.description else []

    if step.action is Action.SIGN_IN:
        role = step.value or scenario.role or "owner"
        return [*comment, f"await signIn(page, {ts_string(role)});"]

    if step.action is Action.NAVIGATE:
        url = step.target.url or "/"
        return [*comment, f"await page.goto({ts_string(url)});"]

    if step.action is Action.CLICK and step.target.selector:
        return [*comment, f"await page.{step.target.selector.playwright()}.click();"]

    if step.action is Action.FILL and step.target.selector:
        return [
            *comment,
            f"await page.{step.target.selector.playwright()}.fill({ts_string(step.value or '')});",
        ]

    if step.action is Action.WAIT_FOR and step.target.selector:
        return [
            *comment,
            f"await expect(page.{step.target.selector.playwright()}).toBeVisible();",
        ]

    return [*comment, f"// unsupported step: {step.action.value}"]


def _assertion(assertion) -> list[str]:  # type: ignore[no-untyped-def]
    """Render one check, carrying its provenance into the generated file.

    The provenance comment is not decoration. When this test fails at 2am,
    whoever reads it needs to know whether the expectation came from a policy
    or from a model's guess.
    """
    lines: list[str] = []
    if assertion.source:
        lines.append(f"// {assertion.provenance.value}: {assertion.source}")

    selector = assertion.target.selector
    if assertion.kind is AssertionKind.VISIBLE and selector:
        lines.append(f"await expect(page.{selector.playwright()}).toBeVisible();")
    elif assertion.kind is AssertionKind.TEXT and selector:
        lines.append(
            f"await expect(page.{selector.playwright()})"
            f".toContainText({ts_string(assertion.expected or '')});"
        )
    elif assertion.kind is AssertionKind.URL:
        lines.append(f"await expect(page).toHaveURL(/{assertion.expected or '.*'}/);")
    elif assertion.kind is AssertionKind.NO_CONSOLE_ERRORS:
        lines.append("// console errors are collected by the runner, not asserted here")
    else:
        lines.append(f"// unsupported assertion: {assertion.kind.value}")

    return lines
