"""Authorization tests, generated directly from row-level security policies.

The cheapest high-value tests this tool produces. The policy already states the
expectation — "a user may read rows where ``auth.uid() = user_id``" — so no
inference is involved, and the failure it catches is one tenant reading
another's data.

Two shapes, chosen by what the deployment permits:

**Leak test** (default, works read-only). Sign in as one role, read everything
the policy lets you read, and assert that no returned row belongs to anyone
else. This needs no writes, so it is safe against a shared deployment, and it
catches the real bug: a policy that is missing, disabled, or too permissive.

**Denial test** (needs a disposable deployment). Create a row as one user, then
attempt the guarded operation as another and require it to fail. Stronger,
because it proves the policy actively refuses rather than merely that no data
happened to leak — but it writes, so it is only emitted where writes are
allowed.

Generated as Vitest against ``@supabase/supabase-js``: no browser, so these run
in seconds.
"""

from __future__ import annotations

from typing import ClassVar

from testtrout.authoring.base import EmittedFile, header, ts_string
from testtrout.domain.config import Config
from testtrout.domain.scenario import Scenario

SETUP_PATH = "tests/trout/_supabase.ts"

SETUP_SOURCE = """\
// Generated by testtrout. Shared helpers for authorization tests.
//
// Do not edit. Regenerated by `qa generate`.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `${name} is not set. Authorization tests need it — see .env and .trout/config.yaml.`,
    );
  }
  return value;
}

/** Sign in as a seeded test user and return an authenticated client. */
export async function clientForRole(role: string): Promise<SupabaseClient> {
  const upper = role.toUpperCase().replace(/-/g, '_');
  const client = createClient(required('SUPABASE_URL'), required('SUPABASE_ANON_KEY'));
  const { error } = await client.auth.signInWithPassword({
    email: required(`TROUT_${upper}_EMAIL`),
    password: required(`TROUT_${upper}_PASSWORD`),
  });
  if (error) {
    throw new Error(`could not sign in as ${role}: ${error.message}`);
  }
  return client;
}

/** The signed-in user's id, used to check row ownership. */
export async function userId(client: SupabaseClient): Promise<string> {
  const { data, error } = await client.auth.getUser();
  if (error || !data.user) {
    throw new Error(`could not read the signed-in user: ${error?.message ?? 'no user'}`);
  }
  return data.user.id;
}
"""


class RlsEmitter:
    """Emits Vitest authorization tests from row-level security policies."""

    id: ClassVar[str] = "rls-vitest"
    handles: ClassVar[tuple[str, ...]] = ("authorization",)

    def emit(self, scenario: Scenario, config: Config) -> EmittedFile:
        """Compile one authorization scenario."""
        table = _table(scenario)
        owner_column = _owner_column(scenario)
        role = scenario.role or "owner"
        path = f"tests/trout/authz/{scenario.id.replace(':', '_')}.test.ts"

        notes: list[str] = []
        if owner_column is None:
            notes.append(
                f"No ownership column was identified on {table}. The generated test asserts "
                "only that the read succeeds, which proves very little — tell the tool which "
                "column scopes a row to a user and regenerate."
            )

        body = _leak_test(scenario, table, owner_column, role)
        notes.append(
            "This is a leak test: it proves no row you can read belongs to someone else. "
            "It runs read-only, so it is safe against a shared deployment."
        )

        return EmittedFile(
            path=path,
            content=header(scenario.id) + "\n" + body,
            shared={SETUP_PATH: SETUP_SOURCE},
            notes=notes,
        )


def _table(scenario: Scenario) -> str:
    """The table under test, from the scenario's steps or assertions."""
    targets = [step.target for step in scenario.when] + [a.target for a in scenario.then]
    return next((t.table for t in targets if t.table), "unknown_table")


def _owner_column(scenario: Scenario) -> str | None:
    """The column that scopes a row to a user, if the proposer identified one."""
    for fixture in scenario.fixtures:
        owner = fixture.columns.get("__owner_column__")
        if owner:
            return owner
    return None


def _leak_test(scenario: Scenario, table: str, owner_column: str | None, role: str) -> str:
    """Assert that nothing readable belongs to another user."""
    evidence = [f"//   - {a.source}" for a in scenario.then if a.source]
    evidence_block = "\n".join(evidence)

    if owner_column is None:
        assertion = """\
    // No ownership column was identified, so this can only check that the read
    // itself is permitted. Supply the column and regenerate for a real test.
    expect(error, `reading ${'{'}TABLE{'}'} failed: ${'{'}error?.message{'}'}`).toBeNull();"""
    else:
        assertion = f"""\
    expect(error, `reading ${{TABLE}} failed: ${{error?.message}}`).toBeNull();

    const foreign = (data ?? []).filter((row) => row[{ts_string(owner_column)}] !== me);
    expect(
      foreign,
      `${{foreign.length}} row(s) in ${{TABLE}} belong to another user but were readable. ` +
        'Row-level security is missing, disabled, or too permissive.',
    ).toHaveLength(0);"""

    return f"""\
import {{ describe, expect, it }} from 'vitest';

import {{ clientForRole, userId }} from '../_supabase';

const TABLE = {ts_string(table)};

// {scenario.title}
//
// Expectation derived from:
{evidence_block or "//   - (no policy text recorded)"}
describe(`${{TABLE}}: row-level security`, () => {{
  it({ts_string(scenario.title)}, async () => {{
    const client = await clientForRole({ts_string(role)});
    const me = await userId(client);

    const {{ data, error }} = await client.from(TABLE).select('*').limit(500);

{assertion}
  }});
}});
"""
