"""The test emitter contract.

Public API: third-party packages implement this and register under the
``testtrout.emitters`` entry point group, so support for another test runner can
ship separately.

An emitter takes a scenario specification and produces source code. It must not
call a model — by the time a scenario reaches an emitter, every decision has
been made and recorded in the specification. Compilation is mechanical, and
keeping it mechanical is what makes generated tests reproducible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib.metadata import entry_points
from typing import ClassVar, Protocol, runtime_checkable

from testtrout.domain.config import Config
from testtrout.domain.scenario import Scenario

ENTRY_POINT_GROUP = "testtrout.emitters"

GENERATED_HEADER = """\
// Generated by testtrout from {source}
//
// Do not edit this file. It is regenerated from the scenario specification and
// your changes will be lost. Edit {source} and run `trout build`.
"""


@dataclass
class EmittedFile:
    """One generated file, plus anything it needs to run."""

    path: str
    """Repository-relative path."""
    content: str
    shared: dict[str, str] = field(default_factory=dict)
    """Support files written once and reused, keyed by path. Overwriting an
    identical support file is harmless, so emitters need not coordinate."""
    notes: list[str] = field(default_factory=list)
    """Anything the developer must do for this test to run — a seeded row, an
    environment variable, a package to install."""


@runtime_checkable
class TestEmitter(Protocol):
    """Compiles a scenario specification into runnable source."""

    id: ClassVar[str]
    handles: ClassVar[tuple[str, ...]]
    """Scenario kinds this emitter can compile, by :class:`TestKind` value."""

    def emit(self, scenario: Scenario, config: Config) -> EmittedFile:
        """Produce the source for one scenario.

        Must be deterministic: the same specification always produces the same
        bytes, so regenerating an unchanged suite yields an empty diff.
        """
        ...


def load_emitters() -> list[TestEmitter]:
    """Load every registered emitter, skipping any that fail to import."""
    emitters: list[TestEmitter] = []
    for entry in entry_points(group=ENTRY_POINT_GROUP):
        try:
            emitters.append(entry.load()())
        except Exception:
            continue
    return emitters


def select_emitter(scenario: Scenario) -> TestEmitter | None:
    """Pick the emitter that handles this scenario's kind."""
    return next((e for e in load_emitters() if scenario.kind.value in e.handles), None)


def header(scenario_id: str) -> str:
    """The do-not-edit banner, naming the file a developer can actually open.

    Scenario ids contain colons; the files on disk do not. Printing the id here
    would send someone looking for a path that does not exist.
    """
    filename = scenario_id.replace(":", "_").replace("/", "-")
    return GENERATED_HEADER.format(source=f".trout/scenarios/{filename}.yaml")


def ts_string(value: str) -> str:
    """Render a Python string as a TypeScript single-quoted literal."""
    escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{escaped}'"
