"""Detecting and configuring the project's test toolchain.

Generated tests run under Playwright and Vitest, which a Lovable or v0 project
almost never has configured. So the tool writes its own configs, scoped
entirely to ``tests/trout/`` — never touching an existing ``playwright.config.ts``
or ``vitest.config.ts`` at the project root, because clobbering a developer's
own test setup would be unforgivable.

One setting is worth defending: ``retries: 0``. Retrying a failed test hides
the flakiness it should be surfacing, and a suite that quietly retries is a
suite whose green is meaningless. Repeats happen here, deliberately, during
certification.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path

TROUT_TEST_DIR = "tests/trout"

# TypeScript is full of braces, so these use explicit __TOKEN__ placeholders
# rather than str.format. Escaping every brace in a JS template is a bug waiting
# to happen — and did happen, once.
PLAYWRIGHT_CONFIG = """\
// Generated by testtrout. Scoped to tests/trout/ — your own Playwright config,
// if you have one, is untouched.
//
// Do not edit. Regenerated by `trout run`.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  // Both directories hold Playwright specs: browser journeys, and the
  // authorization tests that prove one account cannot see another's data by
  // signing in as each in turn.
  testDir: '.',
  testMatch: ['browser/**/*.spec.ts', 'authz/**/*.spec.ts'],
  // Deliberate: retrying hides the flakiness it should surface. Repeats happen
  // during `trout certify`, where inconsistency is the signal being measured.
  retries: 0,
  fullyParallel: false,
  workers: 1,
  timeout: __TIMEOUT_MS__,
  reporter: [['json', { outputFile: '__REPORT__' }]],
  outputDir: '__ARTIFACTS__',
  use: {
    baseURL: process.env.TROUT_BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
});
"""

VITEST_CONFIG = """\
// Generated by testtrout. Scoped to tests/trout/ — your own Vitest config, if
// you have one, is untouched.
//
// Do not edit. Regenerated by `trout run`.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/trout/endpoint/**/*.test.ts'],
    testTimeout: __TIMEOUT_MS__,
    retry: 0,
    fileParallelism: false,
    reporters: ['json'],
    outputFile: '__REPORT__',
  },
});
"""


@dataclass
class Toolchain:
    """What is available for running tests in this project."""

    root: Path
    package_manager: str = "npm"
    has_playwright: bool = False
    has_vitest: bool = False
    has_supabase_js: bool = False
    has_supabase_cli: bool = False
    problems: list[str] = field(default_factory=list)

    @property
    def runner(self) -> list[str]:
        """The command prefix for running a package binary."""
        return {
            "pnpm": ["pnpm", "exec"],
            "yarn": ["yarn"],
            "bun": ["bunx"],
        }.get(self.package_manager, ["npx", "--no-install"])

    def can_run(self, kind: str) -> bool:
        """Whether a given test kind can execute here.

        Endpoint tests need only Vitest. Requiring ``@supabase/supabase-js``
        alongside it was left over from when signing in meant calling Supabase
        directly; tests now drive the app's own login form, so an application
        that has never heard of Supabase is no longer blocked from running a
        single HTTP test.
        """
        if kind == "browser":
            return self.has_playwright
        return self.has_vitest


def _dependencies(root: Path) -> dict[str, str]:
    """Read package.json dependencies."""
    import json

    try:
        package = json.loads((root / "package.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    deps: dict[str, str] = {}
    for section in ("dependencies", "devDependencies"):
        raw = package.get(section)
        if isinstance(raw, dict):
            deps.update({str(k): str(v) for k, v in raw.items()})
    return deps


def app_root(root: Path) -> Path:
    """Where the JavaScript project actually lives.

    A monorepo keeps its frontend in ``frontend/`` or ``apps/web/``, and the
    repository root has no ``package.json`` at all. Reading dependencies from
    the repository root there finds nothing, so every runner is reported as
    missing and every test comes back "the toolchain is not installed" — a
    confusing way to say "I looked in the wrong directory".
    """
    from testtrout.analysis.detect import find_app_root

    return find_app_root(root) or root


def detect(root: Path) -> Toolchain:
    """Determine what the project can run, and report what it cannot.

    Missing packages are reported with the exact install command rather than
    left to surface as an opaque `npx` failure ten seconds later.
    """
    root = app_root(root)
    deps = _dependencies(root)
    manager = next(
        (
            name
            for lockfile, name in (
                ("pnpm-lock.yaml", "pnpm"),
                ("yarn.lock", "yarn"),
                ("bun.lockb", "bun"),
                ("package-lock.json", "npm"),
            )
            if (root / lockfile).exists()
        ),
        "npm",
    )

    toolchain = Toolchain(
        root=root,
        package_manager=manager,
        has_playwright="@playwright/test" in deps,
        has_vitest="vitest" in deps,
        has_supabase_js="@supabase/supabase-js" in deps,
        has_supabase_cli=shutil.which("supabase") is not None,
    )

    install = {"pnpm": "pnpm add -D", "yarn": "yarn add -D", "bun": "bun add -d"}.get(
        manager, "npm install -D"
    )
    if not toolchain.has_playwright:
        toolchain.problems.append(
            f"@playwright/test is not installed — browser tests cannot run. "
            f"Install it with: {install} @playwright/test && npx playwright install chromium"
        )
    if not toolchain.has_vitest:
        toolchain.problems.append(
            f"vitest is not installed — authorization and endpoint tests cannot run. "
            f"Install it with: {install} vitest"
        )
    return toolchain


def write_configs(root: Path, timeout_seconds: int, report_dir: Path) -> list[str]:
    """Write the scoped Playwright and Vitest configs.

    Returns the repository-relative paths written, so the caller can report
    exactly what appeared in the working tree.
    """
    root = app_root(root)
    directory = root / TROUT_TEST_DIR
    directory.mkdir(parents=True, exist_ok=True)
    timeout_ms = max(timeout_seconds, 1) * 1000

    def project_relative(path: Path) -> str:
        """A path relative to the project root.

        Vitest resolves reporter output and `include` against the working
        directory, and the runner always invokes it from the project root —
        which is why the globs above are written from the root rather than
        from this config's own directory.
        """
        import os

        return os.path.relpath(path, root).replace("\\", "/")

    def config_relative(path: Path) -> str:
        """A path relative to this config file's own directory.

        Playwright is the exception: `outputFile` and `outputDir` resolve
        against the directory holding the config, not the working directory.
        Writing them from the root put every report and screenshot under
        `tests/trout/.trout/`, where nothing looked for them — so a test that
        ran and genuinely failed was reported as never having run.
        """
        import os

        return os.path.relpath(path, directory).replace("\\", "/")

    written: list[str] = []
    for name, template, tokens in (
        (
            "playwright.config.ts",
            PLAYWRIGHT_CONFIG,
            {
                "__REPORT__": config_relative(report_dir / "playwright.json"),
                "__ARTIFACTS__": config_relative(report_dir / "artifacts"),
            },
        ),
        (
            "vitest.config.ts",
            VITEST_CONFIG,
            {"__REPORT__": project_relative(report_dir / "vitest.json")},
        ),
    ):
        content = template.replace("__TIMEOUT_MS__", str(timeout_ms))
        for token, value in tokens.items():
            content = content.replace(token, value)
        (directory / name).write_text(content, encoding="utf-8")
        written.append(f"{TROUT_TEST_DIR}/{name}")
    return written
